export const ACTIONS = {
	SETMAP: "SETMAP",
	INSERT: "INSERT",
	CLEANINSERT: "CLEANINSERT",
	INSERTMULTI: "INSERTMULTI",
	CLEANINSERTMULTI: "CLEANINSERTMULTI",
	REMOVE: "REMOVE",
	REMOVEMULTI: "REMOVEMULTI",
	CLEAR: "CLEAR"
};

export const LAYERTYPES = {
	LINESTRING: "LINESTRING",
	MARKER: "MARKER",
	GEOJSON: "GEOJSON"
};
